name: Action
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Checkout refit
        uses: actions/checkout@v2
        with:
          repository: reactiveui/refit
          path: refit
      - name: Checkout coverlet
        uses: actions/checkout@v2
        with:
          path: coverlet  
      - name: Setup .NET Core SDK 2.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
          include-prerelease: true  
      - name: Generate first refit report
        working-directory: refit
        run: | 
          git fetch --prune --unshallow
          dotnet build
          dotnet test --framework net5.0 --no-build --collect:"XPlat Code Coverage"
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.9
        with:
          reports: 'refit\Refit.Tests\TestResults\*\coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'TextSummary'
          toolpath: 'reportgeneratortool'
      - name: Rename first summary
        run: Rename-Item coveragereport\Summary.txt old.txt
      - name: Pack coverlet master
        working-directory: coverlet
        run: |
          git fetch --prune --unshallow
          dotnet pack -c Release
      - name: Generate second refit report
        working-directory: refit
        run: | 
          Remove-Item 'Refit.Tests\TestResults' -Recurse
          dotnet add package coverlet.collector --package-directory ../coverlet/bin/Release/Packages
          dotnet clean
          dotnet build
          dotnet test --framework net5.0 --no-build --collect:"XPlat Code Coverage"
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.9
        with:
          reports: 'refit\Refit.Tests\TestResults\*\coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'TextSummary'
          toolpath: 'reportgeneratortool'
      - name: Rename second summary
        run: Rename-Item coveragereport\Summary.txt master.txt               
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: |
            coveragereport/*.txt