name: Action
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Checkout refit
        uses: actions/checkout@v2
        with:
          repository: reactiveui/refit
          path: refit
      - name: Checkout coverlet
        uses: actions/checkout@v2   
      - name: Setup .NET Core SDK 2.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.1.x'
      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Setup .NET Core SDK 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
          include-prerelease: true  
      - name: Generate first refit report
        working-directory: refit
        run: | 
          git fetch --prune --unshallow
          dotnet build
          dotnet test --framework net5.0 --no-build --collect:"XPlat Code Coverage"
      - name: Pack coverlet master
        run: |
          git fetch --prune --unshallow
          dotnet pack
      - name: Generate second refit report
        working-directory: refit
        run: | 
          dotnet add package coverlet.collector --package-directory ../coverlet/bin/Debug/Packages
          dotnet clean
          dotnet build
          dotnet test --framework net5.0 --no-build --collect:"XPlat Code Coverage"
      - uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: refit\Refit.Tests\TestResults\*\coverage.cobertura.xml